services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_USER=johndoe
      - POSTGRES_DB=mydb
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgresql_data:
